### ISSUE TITLE
Several fixes accidentally reverted in BitShares branch

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#637]
Much too aggressive revert in commit https://github.com/bitshares/bitshares-2/commit/b175cc7feb4accaeab5e85ebfcddfe7d2264c422

Affected commits (I'll check these off as I merge them into BitShares):
- [x] 26663509789b60390c02a977cd05dc3a96e57310 (Fix iteration logic in _handle_message_calls_in_progress shutdown loop to handle concurrent modification #598)
- [x] 3c6f4ce22359f08e1436c3a645a03b3d95e56521 (Fix price feed expiration check #540, fixed in previous release by e955b06c42cf93c42414f74cd54b94092451892e)
- [x] 92cfb96c618e1c051dd7a7224e5392d56c496c06 (Test serialization of extensions #599)
- [x] a83af9208ea93cdbde9b9ee66eaba5babc7e78fc (ext.hpp:  Fix extension unpacking #599)

These are already in BitShares, it's just that BitShares has a commit which reverts them on top of these commits.  So I'll cherry-pick them into BitShares with a new commit message referencing this commit.  The only hardfork here is the last one, a83af9208ea93cdbde9b9ee66eaba5babc7e78fc which will require its own hardfork.  As extensions can't be included because the bug in #599 is still live, it suffices to bump the hardfork time for #599 for the next release.
